In [1]:
d = (1,2,3,4,5)
print(type(d))

<class 'tuple'>


In [2]:
a = int(input())
print(a)

5


In [3]:
import numpy as np # np라는 이름으로 축약하여 numpy를 실행하겠다.

a = np.array([1, 2.5, 4, 5.5, 7.0])
a_re = a.reshape(5,1)

#a[3:]
"""
세 함수 한 번에 출력 안 됨 - 마지막 함수만 출력되는 것 같음
print 괄호 안에 함수값 같이 넣어주면 같이 쓸 수 있음
함수 이름만 쓰면 동작만 되는데 그냥 마지막 거 같이 출력해주는 듯
"""
#a.sum() # np.array로 생성한 변수 a의 합을 출력
#a.std() # np.array로 생성한 변수 a의 표준편차를 출력
#a.cumsum() # np.array로 생성한 변수 a의 누적 합을 출력

"""
print 할 때 정수형이 실수형으로 변환되면서 생기는 0이 출력되지 않고 공백처리됨
,로 구분이 안 되고 출력됨 - 다른 코드들 찾아봐도 이런 거 보니까 원래 구분 없이 출력되는 듯
아래 코드에서 실험해본 바로는 정수형, 실수형만 각각 있을 때는 괜찮은데 섞이면 문제 발생
sep="" 함수로 출력해보려 했는데 numpy 배열 안에서는 sep이 동작 안하는 듯 함 ","로 입력해도 그대로
reshape으로 나눠서 출력 해보니 0이 출력 X, 공백처리된 게 맞는 듯 함 왤까...?
!!! : 가장 긴 숫자를 기점으로 전체 공백을 맞추고 소수점 위치를 그에 맞춰서 출력
"""

print(a[3:])
print(a.sum())
print(a.std())
print(a.cumsum())
print(a)
print(a_re*2)
print(a_re**2)
print(np.sqrt(a_re))


[5.5 7. ]
20.0
2.1213203435596424
[ 1.   3.5  7.5 13.  20. ]
[1.  2.5 4.  5.5 7. ]
[[ 2.]
 [ 5.]
 [ 8.]
 [11.]
 [14.]]
[[ 1.  ]
 [ 6.25]
 [16.  ]
 [30.25]
 [49.  ]]
[[1.        ]
 [1.58113883]
 [2.        ]
 [2.34520788]
 [2.64575131]]


In [1]:
import numpy as np
n1 = np.array([3,6,9])
print(n1)
print(n1+5)
print(n1*5)
print(n1/5)

[3 6 9]
[ 8 11 14]
[15 30 45]
[0.6 1.2 1.8]


In [40]:
# numpy.ndarray 클래스를 사용하면 각 차원의 축을 명시적으로 참조 가능
# 특정한 열 선택 가능
b = np.array([a,a**2])
print(b)
print(b.sum(axis=0)) # 축이 0일 경우 세로 축의 합 출력 - 행을 더함
print(b.sum(axis=1)) # 축이 1일 경우 세로 축의 합 출력 - 열을 더함

[[ 1.    2.5   4.    5.5   7.  ]
 [ 1.    6.25 16.   30.25 49.  ]]
[ 2.    8.75 20.   35.75 56.  ]
[ 20.  102.5]


In [43]:
c = np.zeros((2,3), dtype = "l")
# dtype = l : 정수형, f: 복소수형(실수형이랑 같은 말 같음)
print(c)

[[0 0 0]
 [0 0 0]]
